apiVersion: v1
kind: Namespace
metadata:
  name: argocd-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nginx-test-deploy
  namespace: argocd-demo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: argocd-nginx-test
  template:
    metadata:
      labels:
        app: argocd-nginx-test
    spec:
      containers:
      - name: argocd-nginx-test
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-nginx-test-svc
  namespace: argocd-demo
  labels:
    app: argocd-nginx-test
spec:
  type: LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: argocd-nginx-test