apiVersion: v1
kind: Namespace
metadata:
  name: argocd-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-deploy
  namespace: argocd-demo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-svc
  namespace: argocd-demo
  labels:
    app: nginx-demo
spec:
  type: LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-demo